KVM: SVM: Fix compile error when CONFIG_KVM_AMD=y, CONFIG_KVM_AMD_SEV=n
This patch fixes compile errors when CONFIG_KVM_AMD=y, and
CONFIG_KVM_AMD_SEV=n.  This is due to the stub functions are missing
for !CONFIG_KVM_AMD_SEV.  This patch adds stub functions to make it compile.

  CC      arch/x86/kvm/svm/svm.o
/linux/arch/x86/kvm/svm/svm.c: In function 'init_vmcb':
/linux/arch/x86/kvm/svm/svm.c:1367:17: error: implicit declaration of function 'sev_init_vmcb'; did you mean 'init_vmcb'? [-Werror=implicit-function-declaration]
 1367 |                 sev_init_vmcb(svm);
      |                 ^~~~~~~~~~~~~
      |                 init_vmcb
/linux/arch/x86/kvm/svm/svm.c: In function '__svm_vcpu_reset':
/linux/arch/x86/kvm/svm/svm.c:1391:17: error: implicit declaration of function 'sev_es_vcpu_reset'; did you mean 'kvm_vcpu_reset'? [-Werror=implicit-function-declaration]
 1391 |                 sev_es_vcpu_reset(svm);
      |                 ^~~~~~~~~~~~~~~~~
      |                 kvm_vcpu_reset
/linux/arch/x86/kvm/svm/svm.c: In function 'svm_prepare_switch_to_guest':
/linux/arch/x86/kvm/svm/svm.c:1519:17: error: implicit declaration of function 'sev_es_unmap_ghcb' [-Werror=implicit-function-declaration]
 1519 |                 sev_es_unmap_ghcb(svm);
      |                 ^~~~~~~~~~~~~~~~~
/linux/arch/x86/kvm/svm/svm.c:1533:17: error: implicit declaration of function 'sev_es_prepare_switch_to_guest'; did you mean 'svm_prepare_switch_to_guest'? [-Werror=implicit-function-declaration]
 1533 |                 sev_es_prepare_switch_to_guest(svm, hostsa);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 svm_prepare_switch_to_guest
/linux/arch/x86/kvm/svm/svm.c: In function 'io_interception':
/linux/arch/x86/kvm/svm/svm.c:2242:32: error: implicit declaration of function 'sev_es_string_io'; did you mean 'kvm_sev_es_string_io'? [-Werror=implicit-function-declaration]
 2242 |                         return sev_es_string_io(svm, size, port, in);
      |                                ^~~~~~~~~~~~~~~~
      |                                kvm_sev_es_string_io
/linux/arch/x86/kvm/svm/svm.c: In function 'pre_svm_run':
/linux/arch/x86/kvm/svm/svm.c:3565:24: error: implicit declaration of function 'pre_sev_run'; did you mean 'pre_svm_run'? [-Werror=implicit-function-declaration]
 3565 |                 return pre_sev_run(svm, vcpu->cpu);
      |                        ^~~~~~~~~~~
      |                        pre_svm_run
/linux/arch/x86/kvm/svm/svm.c:3565:24: error: 'return' with a value, in function returning void [-Werror=return-type]
 3565 |                 return pre_sev_run(svm, vcpu->cpu);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/linux/arch/x86/kvm/svm/svm.c:3548:13: note: declared here
 3548 | static void pre_svm_run(struct kvm_vcpu *vcpu)
      |             ^~~~~~~~~~~
/linux/arch/x86/kvm/svm/svm.c: In function 'svm_vcpu_after_set_cpuid':
/linux/arch/x86/kvm/svm/svm.c:4375:17: error: implicit declaration of function 'sev_vcpu_after_set_cpuid'; did you mean 'svm_vcpu_after_set_cpuid'? [-Werror=implicit-function-declaration]
 4375 |                 sev_vcpu_after_set_cpuid(svm);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
      |                 svm_vcpu_after_set_cpuid
/linux/arch/x86/kvm/svm/svm.c: In function 'svm_vcpu_deliver_sipi_vector':
/linux/arch/x86/kvm/svm/svm.c:4902:9: error: implicit declaration of function 'sev_vcpu_deliver_sipi_vector'; did you mean 'svm_vcpu_deliver_sipi_vector'? [-Werror=implicit-function-declaration]
 4902 |         sev_vcpu_deliver_sipi_vector(vcpu, vector);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         svm_vcpu_deliver_sipi_vector
cc1: some warnings being treated as errors

Fixes: 5c4f95183b6d ("KVM: SVM: Compile sev.c if and only if CONFIG_KVM_AMD_SEV=y")
Reported-by: Rick Edgecombe <rick.p.edgecombe@intel.com>

update

Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>